defaults:
  - model: lstm_vel
  - dataloader

metrics:
  pose_metrics:
    - ADE
    - FD
  mask_metrics:
    - FDE

evaluate:
  dataset: ???
  persons_num: 1
  skip_num: 0
  batch_size: 1
  shuffle: false
  pin_memory: false
  num_workers: 0
  load_path: ???
  distance_loss: L1
  rounds_num: 1
  train_dataset: ???

predict:
