defaults:
  - _self_
  - data: main
  - model:
  - metrics

dataset: ???
#keypoint_dim: ???
train_keypoint_dim: ???
pred_keypoint_dim: 3
normalize: false
loader: "ours"
use_mask: false
load_path:
rounds_num: 1
device: cuda
keypoint_dim: 3


# added
model_pose_format: ""
metric_pose_format: "xyz"