defaults:
  - _self_
  - shared
  - data: main
  - model:
  - metrics

dataset: ???
normalize: false
use_mask: false
load_path:
csv_save_dir:
rounds_num: 1
device: cuda
eval_uncertainty: false
uncertainty_load_path:
