defaults:
  - _self_
  - data: main
  - model:
  - metrics

dataset: ???
#keypoint_dim: ???
train_keypoint_dim: ???
pred_keypoint_dim: ???
normalize: false
loader: "ours"
use_mask: false
load_path:
rounds_num: 1
device: cuda


# added
obs_frames_num: ???
pred_frames_num: ???
train_pose_format: ???
pred_pose_format: ??? 