defaults:
  - _self_
  - data: main
  - model:
  - metrics

dataset: ???
keypoint_dim: ???
normalize: false
use_mask: false
load_path:
rounds_num: 1
device: cuda


# added
model_pose_format: ""
metric_pose_format: "xyz"