defaults:
  - model: pv_lstm
  - dataloader: base_dataloader
  - metrics: base_metrics
  - share
  - _self_

dataloader:
  batch_size: 1
  shuffle: false

load_path: ???
distance_loss: L1
rounds_num: 1
train_dataset:
