pose_metrics:
  - ADE
  - FDE
  - ade_80
  - ade_160
  - ade_320
  - ade_560
  - ade_720
  - ade_880
  - local_ade
#  - local_fde
#  - VIM
#  - VAM

mask_metrics:
  - accuracy
  - f1_score
  - precision
  - recall