pose_metrics:
  - ADE
  - FDE
  - ade_200
  - ade_400
  - ade_600
  - ade_800
  - ade_1000
#  - ade_880
#  - local_ade
#  - local_fde
#  - VIM
#  - VAM

mask_metrics:
  - accuracy
  - f1_score
  - precision
  - recall