defaults:
  - _self_

official_annotation_path: ???
dataset: ???
data_type: ???
output_name:
obs_frames_num: ???
pred_frames_num: ???
use_video_once: false
annotate_openpifpaf: false
image_dir: ???
joints_annotation_path: ???
is_3D: ???