defaults:
  - shared
  - _self_

official_annotation_path: ???
dataset: ???
data_type: ???
output_name:
use_video_once: false
skip_num: 0
interactive: false
save_total_frames: true

# This is used just for 3DPW
load_60Hz: True