defaults:
  - _self_
  - data: main
  - model: ???
  - optimizer: adam
  - scheduler: reduce_lr_on_plateau
  - metrics

train_dataset: ???
valid_dataset:
epochs: ???
snapshot_interval: ${epochs}
start_epoch: 0
device: cpu #cuda
keypoint_dim: ???
is_noisy: false
use_mask: false
use_dct: false
normalize: false
load_path:
save_dir:
pred_pose_format: euler #temp