defaults:
  - _self_
  - shared
  - data: main
  - model: ???
  - optimizer: adam
  - scheduler: multi_step_lr
  - metrics

train_dataset: ???
valid_dataset:
epochs: ???
snapshot_interval: ${epochs}
start_epoch: 0
device: cpu
use_mask: false
use_dct: false
normalize: false
load_path:
save_dir:
experiment_name: Default
experiment_tag:
mlflow_tracking_uri: