defaults:
  - _self_
  - data: main
  - model: ???
  - optimizer: adamw
  - scheduler: reduce_lr_on_plateau
  - metrics

train_dataset: ???
valid_dataset:
epochs: ???
snapshot_interval: ${epochs}
start_epoch: 0
device: cpu
keypoint_dim: ???
use_mask: false
use_dct: false
normalize: false
load_path:
save_dir:

# added
obs_frames_num: ???
pred_frames_num: ???
model_pose_format: xyz
metric_pose_format: