defaults:
  - _self_
  - shared
  - data: main
  - model: ???
  - optimizer: adam
  - scheduler: multi_step_lr
  - metrics

train_dataset: ???
valid_dataset:
epochs: ???
snapshot_interval: ${epochs}
start_epoch: 0
experiment_name: Default
experiment_tag:
mlflow_tracking_uri:
