defaults:
  - _self_
  - data: main
  - model: ???
  - optimizer: adam
  - scheduler: reduce_lr_on_plateau
  - metrics

train_dataset: ???
valid_dataset:
epochs: ???
snapshot_interval: ${epochs}
start_epoch: 0
device: cuda
train_keypoint_dim: ???
pred_keypoint_dim: ???
is_noisy: false
use_mask: false
use_dct: false
normalize: false
load_path:
save_dir:

# added
obs_frames_num: ???
pred_frames_num: ???
train_pose_format: ???
pred_pose_format: ??? 