defaults:
  - _self_
  - data: main
  - model: ???
  - loss: ???
  - optimizer: adam
  - scheduler: reduce_lr_on_plateau
  - metrics


train_dataset: ???
valid_dataset:
epochs: ???
snapshot_interval: ${epochs}
start_epoch: 0
load_path:
device: cuda
save_dir: