defaults:
  - model: ???
  - loss: ???
  - optimizer: adam
  - scheduler: reduce_lr_on_plateau
  - metrics
  - dataloader
  - _self_

train_dataset: ???
valid_dataset: ???
epochs: ???
snapshot_interval: -1
start_epoch: 0
load_path: