defaults:
  - data: main
  - model: ???
  - shared
  - _self_

dataset: ???
dataset_type: ???
keypoint_dim: 3
showing: future, predicted
use_mask: false
pred_frames_num:
load_path:
index:
device: cuda
images_dir:
save_dir:
normalize: false

data:
  is_visualizing: true