defaults:
  - data: main
  - model:
  - _self_

dataset: ???
dataset_name: ???
ground_truth: false
device: cuda
keypoint_dim: ???
is_noisy: false
use_mask: false
pred_frames_num:
load_path:
index:
completion: false
images_dir:
save_dir:
data:
  is_visualizing: true