defaults:
  - data: main
  - model: ???
  - _self_

dataset: ???
dataset_type: ???
keypoint_dim: ???
showing: future, predicted
normalize: false
is_noisy: false
use_mask: false
pred_frames_num:
load_path:
index:
device: cuda
images_dir:
save_dir:

data:
  is_visualizing: true