defaults:
  - _self_
  - data: main
  - model:

dataset: ???
dataset_name: ???
ground_truth: false
device: cuda
keypoint_dim: ???
use_mask: false
pred_frames_num:
load_path:
index:
images_dir:
save_dir: