dataset_name: ???
keypoint_dim: 2
is_interactive: ???
persons_num: 1
use_mask: false
skip_num: 0
shuffle: false
pin_memory: false
num_workers: 0
batch_size: 256
is_testing: false
is_visualizing: false