defaults:
  - _self_
  - common

type: comp_and_pred
noisy_rate: 0.2
hidden_size: 200
latent_dim: 10
hardtanh_limit: 10
n_layers: 1
dropout_enc: 0
dropout_pose_dec: 0
dropout_mask_dec: 0

loss:
  type: comp_and_pred
  pred_weight: 1
  comp_weight: 1