defaults:
  - _self_
  - common

type: comp&pred
hidden_size: 200
latent_size: 10
hardtanh_limit: 10
n_layers: 1
dropout_enc: 0
dropout_pose_dec: 0
dropout_mask_dec: 0

loss:
  type: comp&pred
  comp_weight: 1