defaults:
  - _self_
  - common

type: comp_pred_pose
autoregressive: false
noise_value: -1000
hidden_size: 200
latent_dim: 10
activation_type: 'none'
hardtanh_limit: 10
n_layers: 1
dropout_enc: 0
dropout_pose_dec: 0
dropout_mask_dec: 0
normalize: ${data.normalize}
metadata_path:

loss:
  type: comp_pred_pose
  pred_weight: 1
  comp_weight: 1
  kl_weight: 0.001
  keypoint_dim: ${keypoint_dim}