defaults:
  - _self_
  - common

type: constant_bone_tcn

n_txcnn_layers: 32
txc_kernel_size: [3, 3]
txc_dropout: 0
n_major_joints: 22
bias: true

device: &device ${device}

loss:
  type: constant_bone_tcn
