defaults:
  - _self_
  - common

type: history_repeats_itself_amass
kernel_size: 10
d_model: 256
in_features: 54
input_n: ${obs_frames_num}
output_n: ${pred_frames_num}
num_stage: 12
dct_n: 35
itera: 1
un_mode: 'default'
init_mode: 'default'

loss:
  type: his_rep_itself_amass
  input_n: ${obs_frames_num}
  output_n: ${pred_frames_num}
  kernel_size: 10
  device: ${device}
  un_mode: 
  itera:
  disp_reg: false
  disp_thresh: 
  disp_lambda: 