defaults:
  - _self_
  - common

type: history_repeats_itself
kernel_size: 10
d_model: 256
in_features: 66
input_n: ${obs_frames_num}
output_n: ${pred_frames_num}
num_stage: 12
dct_n: 20
itera: 1
un_mode: 'default'
loss:
  type: his_rep_itself
  output_n: ${pred_frames_num}
  kernel_size: 10
  device: ${device}
  un_mode: 