defaults:
  - _self_
  - common

type: my_st_transformer #new

n_major_joints: 22 # 18 # 22
diff_layers: 3
diff_channels: 64
diff_nheads: 8

model_is_unconditional: 0
model_timeemb: 128
model_featureemb: 16

# can be human3.6m , AMASS, 3DPW, none
pre_post_process: human3.6m

device: &device ${device}

# loss:
#   type: mpjpe
#   nJ: 32

loss:
  device: ${device}
  type: pua_loss
  tasks: TJ
  nT: 10
  nJ: 32 # 32
  time_prior: sig5
  action_list: ["walking", "eating", "smoking", "discussion", "directions", "greeting", "phoning", "posing", "purchases", "sitting", "sittingdown", "takingphoto", "waiting", "walkingdog", "walkingtogether"]
  clipMinS: -1
  clipMaxS:
  init_mean: 3.5
