defaults:
  - _self_
  - common

type: pgbig

python main_h36m.py --data_dir [dataset path] --input_n 10 --output_n 25 --skip_rate 1 --batch_size 16 --test_batch_size 32 --in_features 66 --cuda_idx cuda:0 --lr_now 0.005 --epoch 50 --test_sample_num -1

kernel_size: 10 # must be 10. Also obs_frames_num must be 10 to match the kernel size
d_model: 16
dct_n: 35 # usually obs_frames_num + pred_frames_num
in_features: 66 # How many features are in a frame? Probably 3 * n_joints. 66 for Human3.6M
num_stage: 12
drop_out: 0.3

# can be human3.6m , AMASS, 3DPW, none
pre_post_process: human3.6m

device: &device ${device}

loss:
  device: ${device}
  pre_post_process: human3.6m # Should be excatly like the one in the model
  type: pgbig_loss
  inner_type: HUAL # if you want to use the HUAL loss, set this to HUAL. otherwise set it to something else and not None. In that case it will use the original loss function.
  tasks: STJ # use S if you want each stage be a seperate task
  nT: 35 # must be obs_frames_num + pred_frames_num
  nJ: 22 # 18 for AMASS/3DPW, 22 for Human3.6M
  time_prior: sig5
  action_list: ["walking", "eating", "smoking", "discussion", "directions", "greeting", "phoning", "posing", "purchases", "sitting", "sittingdown", "takingphoto", "waiting", "walkingdog", "walkingtogether"]
  clipMinS: -1
  clipMaxS:
  init_mean: 3.5 # 3.5 for Human3.6M, 3 for AMASS/3DPW
