defaults:
  - _self_
  - common

type: pv_lstm_comp
autoregressive: false
noise_value: -1000
hidden_size: 200
activation_type: 'hardtanh'
hardtanh_limit: 10
n_layers: 1
dropout_enc: 0
dropout_pose_dec: 0
dropout_mask_dec: 0

loss:
  type: pv_lstm_comp
  keypoint_dim: ${keypoint_dim}