defaults:
  - _self_
  - common

type: sp_tcn


T_in: ${obs_frames_num}
T_out: ${pred_frames_num}
n_major_joints: 22
n_layers: 3
sksize: [1,1]
tksize: [1,11]

tags: []


device: &device ${device}

loss:
  type: spherical_tcn
