defaults:
  - _self_
  - common

type: st_transformer_pgbig

stages: 3

n_major_joints: 22 # 18 # 22
diff_layers: 3
diff_channels: 64
diff_nheads: 8

model_is_unconditional: 0
model_timeemb: 128
model_featureemb: 16

pred_residual: False
use_skip: True

# can be human3.6m , AMASS, 3DPW, none
pre_post_process: human3.6m

device: &device ${device}

loss:
  device: ${device}
  stages: 3
  type: st_transformer_pgbig_loss
  inner_type: HUAL # ORIGINAL # HUAL # if you want to use the HUAL loss, set this to HUAL. otherwise set it to something else and not None. In that case it will use the original loss function.
  tasks: STJ # use S if you want each stage be a seperate task
  nT: 25 # pred_frames_num
  nJ: 32 # 18 for AMASS/3DPW, 32 for Human3.6M
  time_prior: sig5
  action_list: ["walking", "eating", "smoking", "discussion", "directions", "greeting", "phoning", "posing", "purchases", "sitting", "sittingdown", "takingphoto", "waiting", "walkingdog", "walkingtogether"]
  clipMinS: -1
  clipMaxS:
  init_mean: 3.5 # 3.5 for Human3.6M, 3 for AMASS/3DPW