defaults:
  - _self_
  - common

type: st_transformer

n_major_joints: 22
diff_layers: 3
diff_channels: 64
diff_nheads: 8

model_is_unconditional: 0
model_timeemb: 128
model_featureemb: 16


device: &device ${device}

loss:
  type: task_dependent_uncertainty_loss
  squared: False
  action_aware: False
  joint_aware: False
  time_aware: False
  device: ${device}
  # type: st_transformer_loss

# loss:
#   type: st_transformer_loss
