defaults:
        - _self_
        - common
type: transnet
num_encoder_layers: 1
num_decoder_layers: 1
d_model: 96
nhead: 8
dim_feedforward: 16
dropout: 0.5

# num_encoder_layers: 4
# num_decoder_layers: 4
# d_model: 128
# nheads: 2
# dim_feedforward: 16
# dropout: 0.5
# init_fn_name: xavier
# pre_normalization: true
# pose_embedding_type: gcn_enc
# pos_enc_beta: 500
# pos_enc_alpha: 10
# use_class_token: false
# predict_activity: &predict_activity true
# non_autoregressive: true

# include_last_obs: &include_last_obs false
# pad_decoder_inputs: &pad_decoder_inputs true


# # data related
# pose_format: &model_pose_format ${model_pose_format}
# metric_pose_format: ${metric_pose_format}
# future_frames_num: &pred_frames_num ${pred_frames_num} # convert to pred frames num which is in common

# n_major_joints: &n_major_joints 21
# n_joints: &n_joints 21
# n_h36m_joints: 32
# pose_dim: ${keypoint_dim}
# num_activities: &num_activities 15

# device: &device ${device}
# consider_uncertainty: &consider_uncertainty false

loss:
        type: mse_pose
